name: Merge with SubKt and upload merged subs

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: main
jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Cache gradle
        uses: actions/cache@v3
        with:
          path: main/.gradle
          key: ${{ runner.os }}-1-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-1-gradle-

      - name: Get list of files
        run: |
          # TRIGGER WARNING: Horrible shell oneliner below. Reader discretion is advised.
          echo mergeTasks=$(find [0-9][0-9]* -type f -name '*en.ass' | sort \
            | grep -v ' extended ' \
            | grep -v ' alternate ' \
            | sed -e '/^00/s/\/[a-zA-Z ]* en.ass$/ en.ass/' -e 's|00 Cover Stories and Specials/|00/00/specials |' \
            | cut -d '/' -f 3 \
            | sed -e 's/^/mergeAll./' -e 's/ en.ass$//' -e 's/ /_/' \
            | paste -s -d ' ') >> $GITHUB_ENV

          echo mergeTasksExtended=$(find [0-9][0-9]* -type f -name '*extended en.ass' | sort \
            | sed -e '/^00/s/\/[a-zA-Z ]* en.ass$/ en.ass/' -e 's|00 Cover Stories and Specials/|00/00/specials |' \
            | cut -d '/' -f 3 \
            | sed -e 's/^/mergeAll./' -e 's/ extended en.ass$//' -e 's/ /_/' \
            | paste -s -d ' ') >> $GITHUB_ENV

          echo mergeTasksAlternate=$(find [0-9][0-9]* -type f -name '*alternate en.ass' | sort \
            | sed -e '/^00/s/\/[a-zA-Z ]* en.ass$/ en.ass/' -e 's|00 Cover Stories and Specials/|00/00/specials |' \
            | cut -d '/' -f 3 \
            | sed -e 's/^/mergeAll./' -e 's/ alternate en.ass$//' -e 's/ /_/' \
            | paste -s -d ' ') >> $GITHUB_ENV

      - name: Merge with SubKt
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ env.mergeTasks }}
          build-root-directory: main

      - name: Merge with SubKt (Extended Versions)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: -Pex ${{ env.mergeTasksExtended }}
          build-root-directory: main

      - name: Merge with SubKt (Alternate Versions)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: -Pex ${{ env.mergeTasksAlternate }}
          build-root-directory: main

      - name: Push Subs
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Automated upload of merged subtitles" || true
          git push
