name: Merge with SubKt and upload merged subs

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

defaults:
  run:
    working-directory: main
jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up JDK 11
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          build-root-directory: main

      - name: Get list of files
        run: |
          # TRIGGER WARNING: Horrible shell oneliner below. Reader discretion is advised.
          echo mergeTasks=$(find [0-9][0-9]* -type f -name '*en.ass' | sort \
            | grep -v ' extended ' \
            | grep -v ' alternate ' \
            | sed -e '/^00/s/\/[a-zA-Z ]* en.ass$/ en.ass/' -e 's|00 Cover Stories and Specials/|00/00/specials |' \
            | cut -d '/' -f 3 \
            | sed -e 's/^/mergeAll./' -e 's/ en.ass$//' -e 's/ /_/' \
            | paste -s -d ' ') >> $GITHUB_ENV

          echo mergeTasksExtended=$(find [0-9][0-9]* -type f -name '*extended en.ass' | sort \
            | sed -e '/^00/s/\/[a-zA-Z ]* en.ass$/ en.ass/' -e 's|00 Cover Stories and Specials/|00/00/specials |' \
            | cut -d '/' -f 3 \
            | sed -e 's/^/mergeAll./' -e 's/ extended en.ass$//' -e 's/ /_/' \
            | paste -s -d ' ') >> $GITHUB_ENV

          echo mergeTasksAlternate=$(find [0-9][0-9]* -type f -name '*alternate en.ass' | sort \
            | sed -e '/^00/s/\/[a-zA-Z ]* en.ass$/ en.ass/' -e 's|00 Cover Stories and Specials/|00/00/specials |' \
            | cut -d '/' -f 3 \
            | sed -e 's/^/mergeAll./' -e 's/ alternate en.ass$//' -e 's/ /_/' \
            | paste -s -d ' ') >> $GITHUB_ENV

      - name: Merge with SubKt
        run: ./gradlew ${{ env.mergeTasks }}

      - name: Merge with SubKt (Extended Versions)
        run: ./gradlew -Pex ${{ env.mergeTasksExtended }}

      - name: Merge with SubKt (Alternate Versions)
        run: ./gradlew -Palt ${{ env.mergeTasksAlternate }}

      - name: Push Subs
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Automated upload of merged subtitles" || true
          git push
